### ISSUE TITLE
usare la versione nightly di rust in rust.yaml

### ISSUE THREAD

**Issue by lucat1** [csunibo/course-description-merged#14]
Nella action `rust.yaml`, di cui non capisco l'utilita' btw, non viene specificata l'installazione di rust, quindi di base usa la versione stable che non supporta una feature che usiamo. Tocca usare come nella action per generare il file mettendo tipo:
```yaml
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
```
